### ISSUE TITLE
Quadrant should support configuration-cache

### ISSUE THREAD

**Issue by marcellogalhardo** [gaelmarhic/Quadrant#7] opened 2021-05-27 14:24 UTC
When enabling [configuration-cache](https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:usage) with quadrant by placing `org.gradle.unsafe.configuration-cache=true` to your root `gradle.properties`, the compilation will fail with the following error:

```
Configuration cache state could not be cached: field 'processor$delegate' from type 'com.gaelmarhic.quadrant.tasks.GenerateActivityClassNameConstants': error writing value of type 'kotlin.SynchronizedLazyImpl'
> Configuration cache state could not be cached: field 'value' from type 'kotlin.InitializedLazyImpl': error writing value of type 'com.gaelmarhic.quadrant.processors.GenerateActivityClassNameConstantProcessor'
   > Configuration cache state could not be cached: field 'manifestParsingHelper' from type 'com.gaelmarhic.quadrant.processors.GenerateActivityClassNameConstantProcessor': error writing value of type 'com.gaelmarhic.quadrant.helpers.ManifestParsingHelper'
      > Configuration cache state could not be cached: field 'jaxbUnMarshaller$delegate' from type 'com.gaelmarhic.quadrant.helpers.ManifestParsingHelper': error writing value of type 'kotlin.SynchronizedLazyImpl'
         > Implementation of JAXB-API has not been found on module path or classpath.
```

**Comment by gaelmarhic** [comment] 2021-06-24 15:51
Hey @marcellogalhardo.

Thank you for bringing up this issue.

I have been investigating and I am able to reproduce it.

The issue described in the aforementioned stacktrace seems to happen because the project is compiled against JDK 11, which does not support JAXB anymore. For this reason, I have decided to drop the usage of JAXB in favor of Jackson for XML parsing: #8 .

However, after this, I am getting another issue (which actually happens on any JDK):

```
Could not load the value of field `_locale` of `com.fasterxml.jackson.databind.util.StdDateFormat` bean found in field `_dateFormat` of `com.fasterxml.jackson.databind.cfg.BaseSettings` bean found in field `_base` of `com.fasterxml.jackson.databind.DeserializationConfig` bean found in field `_deserializationConfig` of `com.fasterxml.jackson.dataformat.xml.XmlMapper` bean found in field `value` of `kotlin.InitializedLazyImpl` bean found in field `objectMapper$delegate` of `com.gaelmarhic.quadrant.helpers.ManifestParsingHelper` bean found in field `manifestParsingHelper` of `com.gaelmarhic.quadrant.processors.GenerateActivityClassNameConstantProcessor` bean found in field `value` of `kotlin.InitializedLazyImpl` bean found in field `processor$delegate` of task `:app:generateActivityClassNameConstants` of type `com.gaelmarhic.quadrant.tasks.GenerateActivityClassNameConstants`.
> java.lang.reflect.InvocationTargetException (no error message)
```

I will contact Gradle and try to understand what is happening.
I will let you know when I have any updates.

Thanks.

**Comment by gaelmarhic** [comment] 2021-08-01 18:29
Hey @marcellogalhardo .

I am delighted to tell you that I finally was able to overcome the remaining issues in order to add support for `Gradle's Configuration Cache` to `Quadrant`.

The solution is in #8. It has not been merged yet.

I have done quite a thorough testing myself and everything seems to be working fine, except for [this](https://github.com/gaelmarhic/Quadrant/tree/add-support-gradle-configuration-cache#troubleshooting), which is an edge case and which does not seem directly related to `Quadrant`.

Before I merge it to `master`, would you mind testing it on your project to make sure it works well for you too?

You just need to:
1) Download `Quadrant` from the following branch [branch](https://github.com/gaelmarhic/Quadrant/tree/add-support-gradle-configuration-cache).
2) Open the project with `IntelliJ`.
3) Run the `uploadArchives` task from the `Upload` group. A folder called `mavenrepo` will therefore be generated at the root of your `Quadrant` project.
4) In your Android project, in the root `build.gradle` file, add the following buildscript repository:
```
buildscript {
    repositories {
        maven {
            url uri("your_quadrant_project_path/Quadrant/mavenrepo")
        }
    }
```
5) Still in the root `build.gradle` file, use `classpath "com.gaelmarhic:quadrant:1.5"` instead of `classpath "gradle.plugin.com.gaelmarhic:quadrant:$version"`.

Let me know how it goes!

Thanks a lot!

Gaël

**Comment by gaelmarhic** [comment] 2021-08-04 17:31
@marcellogalhardo, regarding the edge case I was talking about in my previous comment, never mind.
It is an issue on Kotlin Gradle plugin and the fix is in one of the next versions to come.
https://medium.com/@gaelmrc/hey-ivan-aa5578745020

Therefore, I have deleted the section I had previously added to the README.

Cheers!

**Comment by marcellogalhardo** [comment] 2021-09-09 12:37
Hey @gaelmarhic, sorry for the long delay to answer. I tested it locally inside our project and I can confirm your changes are working as expected. Thank you a lot for the improvement and your work in supporting configuration cache.

**Comment by gaelmarhic** [comment] 2021-09-17 17:21
Hey @marcellogalhardo !

The corresponding PR (#8) has been merged and a new release has been made:
https://github.com/gaelmarhic/Quadrant/releases/tag/v1.6
https://plugins.gradle.org/plugin/com.gaelmarhic.quadrant

Please, remember that, even though `Quadrant` now supports it, Gradle Configuration Cache is still experimental, and it still has some issues.
For example, if you run into an error of type `e: Source file or directory not found: /Users/Developer/Desktop/QuadrantTest/app/build/generated/source/quadrant/com/gaelmarhic/quadrant/QuadrantConstants.kt`, it is probably  because of this issue: https://youtrack.jetbrains.com/issue/KT-46651. In that case, update the version of Kotlin Gradle plugin to at least 1.5.30-M1 in your Android project.

Hope this helps.

Cheers!

Gaël

**Closed as completed** 2021-09-17 17:21 UTC
